LIST = [['Albania','Ronela Hajati','"Sekret"',1],
['Latvia','Citi Zēni','"Eat Your Salad"',1],
['Lithuania','Monika Liu','"Sentimentai"',1],
['Switzerland','Marius Bear','"Boys Do Cry"',1],
['Slovenia','LPS','"Disko"',1],
['Ukraine','Kalush Orchestra','"Stefania"(Стефанія)',1],
['Bulgaria','Intelligent Music Project','"Intention"',1],
['Netherlands','S10','"De diepte"',1],
['Moldova','Zdob și Zduband & Frații Advahov','"Trenulețul"',1],
['Portugal','Maro','"Saudade, saudade"',1],
['Croatia','Mia Dimšić','"Guilty Pleasure"',1],
['Denmark','Reddi','"The Show"',1],
['Austria','Lumix feat. Pia Maria','"Halo"',1],
['Iceland','Systur','"Með hækkandi sól"',1],
['Greece','Amanda Georgiadi Tenfjord','"Die Together"',1],
['Norway','Subwoolfer','"Give That Wolf a Banana"',1],
['Armenia','Rosa Linn','"Snap"',1],
['Finland','The Rasmus','"Jezebel"',1],
['Israel','Michael Ben David','"I.M"',1],
['Serbia','Konstrakta','"In corpore sano"',1],
['Azerbaijan','Nadir Rustamli','"Fade to Black"',1],
['Georgia','Circus Mircus','"Lock Me In"',1],
['Malta','Emma Muscat','"I Am What I Am"',1],
['San Marino','Achille Lauro','"Stripper"',1],
['Australia','Sheldon Riley','"Not the Same"',1],
['Cyprus','Andromache','"Ela"(Έλα)',1],
['Ireland','Brooke','"That`s Rich"',1],
['North Macedonia','Andrea','"Circles"',1],
['Estonia','Stefan','"Hope"',1],
['Romania','WRS','"Llámame"',1],
['Poland','Ochman','"River"',1],
['Montenegro','Vladana','"Breathe"',1],
['Belgium','Jérémie Makiese','"Miss You"',1],
['Sweden','Cornelia Jakobs','"Hold Me Closer"',1],
['Czech Republic','We Are Domi','"Lights Off"',1],
['Italy','Mahmoodand & Blanco','"Brividi"',1],
['France','Alvanand & Ahez','"Fulenn"', 1],
['Germany','Malik Harris','"Rockstars"',1],
['Spain','Chanel','"SloMo"',1],
['United Kingdom','Sam Ryder','"Space Man"',1]]